config/routes.rb
Rails.application.routes.draw do
  root 'animes#index'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  get 'get_image/:id', to: 'users#get_image'
  resources :users, only: [:index, :new, :create, :destroy, :edit, :get_image]
  resources :animes, only: [:index, :new, :create, :destroy, :edit, :update]
  resources :likes, only: [:create, :destroy]
  resources :bads, only: [:create, :destroy]

end

app/models/anime.rb
class Anime < ApplicationRecord
  validates :message, presence: true, length: {maximum: 140}

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :bads,  dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :bad_users, through: :bads, source: :user

  def like(user)
    likes.create(user_id:user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id:user.id).destroy
  end
  
  def liked?(user)
    like_users.include?(user)
  end
  
  def bad(user)
    bads.create(user_id:user.id)
  end
  
  def unbad(user)
    bads.find_by(user_id:user.id).destroy
  end
  
  def bad?(user)
    bad_users.include?(user)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
class Bad < ApplicationRecord
    belongs_to :user
    belongs_to :anime
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :anime
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true, uniqueness: true
#  validates :pass, presence: true, length: {minimum: 4}
  validates :password, presence: true, confirmation: true  
  

  has_many :animes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bads, dependent: :destroy
  has_many :like_animes, through: :likes, source: :anime
  has_many :bad_animes, through: :bads, source: :anime

  attr_accessor :password, :password_confirmation

  mount_uploader :image, ImageUploader

  def password=(val)
    if val.present?
      self.pass = BCrypt::Password.create(val)
    end
    @password= val
  end
  
  def self.authenticate(uid, pass)
    user = User.find_by(uid: uid)

    if user and BCrypt::Password.new(user.pass) == pass
      user
    else
      nil
    end
  end

end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def index
    @animes = Anime.all
    @anime = Anime.new
    @like_ranks = Anime.find(Like.group(:anime_id).order('count(anime_id) desc').limit(3).pluck(:anime_id))
    @bad_ranks = Anime.find(Bad.group(:anime_id).order('count(anime_id) desc').limit(3).pluck(:anime_id))
  end

  def new
    @anime = Anime.new
  end

  def create
    #default_scope -> { order(created_at: :asc) }
    @anime = Anime.all.order(created_at: :asc)
    user_id = User.find_by(uid: session[:login_uid]).id
    @anime = Anime.new(message: params[:anime][:message],title: params[:anime][:title], user_id: user_id)
    #params.require(:user).permit(:image)
    if @anime.save
      redirect_to animes_path
    else
      redirect_to animes_path
     #render new_anime_path
    end
  end
  
  def edit
    @anime = Anime.find(params[:id])
    #@user = User.new
    #render "new"
  end

  def update
     @anime = Anime.find(params[:id])
     @anime.update(message: params[:anime][:message],title: params[:anime][:title], user_id: user_id)
    if anime.save
      redirect_to animes_path
    else
       render 'edit'
       #render :edit
    end
  end
  
  def destroy
    anime = Anime.find(params[:id])
    anime.destroy
    redirect_to animes_path
  end
  
  private
    def user_params
      params.require(:user).permit(:content, :image)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    
    private
    def current_user
        if session[:login_uid]
           User.find_by(uid:session[:login_uid])
        end
    end
    helper_method:current_user

end

app/controllers/bads_controller.rb
class BadsController < ApplicationController
  def create
   anime = Anime.find(params[:anime_id])
    unless anime.bad?(current_user)
      anime.bad(current_user)
    end
    redirect_to root_path
  end

  def destroy
    anime = Anime.find(params[:id])
    if anime.bad?(current_user)
      anime.unbad(current_user)
    end
    redirect_to root_path
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    anime = Anime.find(params[:anime_id])
   #if @bad= Bad.find_by(user_id: current_user.id, anime_id: params[:anime_id])
   #   @bad.destroy
   #end
    unless anime.liked?(current_user)
      anime.like(current_user)
    end
    redirect_to root_path
  end

  def destroy
    anime = Anime.find(params[:id])
    if anime.liked?(current_user)
      anime.unlike(current_user)
    end
    redirect_to root_path
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def login
    @user = User.authenticate(params[:uid], params[:pass])
    if @user
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      #render top_login_path
      'error'
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(
      uid: params[:user][:uid],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
      image: params[:user][:image]
      )
      #params.require(:user).permit(:image)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
  
  def edit
    @anime = Anime.find(params[:id])
  end

  def edit
   @user = User.find(params[:id])
   @user.update(message: params[:anime][:message])
   @user.update(title: params[:anime][:title])
    if user.save
      redirect_to users_path
    else
       render 'edit'
       #render :edit
    end
  end
  
  def get_image
#    user = User.find(params[:id])
#    send_data user.file, disposition: :inline, type:'image/png'
  
  @user = User.find_by(id: params[:id])
  #画像データが送信された場合
    if params[:image]
      #データベースに保存するファイル名はユーザーのid.jpgとする
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image}",image.read)
    end
  end
  
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bads_helper.rb
module BadsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/edit.html.erb
<div style= "margin-bottom: 30px">
  <h1>編集フォーム</h1>
</div>
<%= form_for @anime, url: {action: :update} do |f| %>
  <h3>アニメタイトル</h3>
  <p>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <h3>感想</h3>
  <p>
    <%= f.text_area :message, class: 'form-control' %>
  </p>
  <p>
    <%= f.submit '投稿する', class: 'btn btn-success' %>
  </p>
<% end %>

app/views/animes/index.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>
<% if @anime.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @anime.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<% if current_user %>
  <%= form_for @anime, url: {action: :create} do |f| %>
  <p>
    <h3>アニメタイトル</h3>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <br>
    <h3>感想</h3>
    <%= f.text_area :message, class: 'form-control' %>
    <br>
    <%= f.submit '送信', class: 'btn btn-success'%>
  </p>
  <% end %>
<% end %>
<br>
<br>
<h1>みんなの投稿</h1>
<br>


<% @animes.each do |t| %>
  <p>
    <%#<img src="<%= "/user_images/#{@user.image}" %>
    <%#<% if anime.picture? %>
      <%#<%= image_tag @user.image.url %>
      <%= image_tag 'hito.png', class:"profile_img", :size =>'40x40' %>
      <%#<%= image_tag "/get_image/#{t.id}" %>
      <%= User.find(t.user_id).uid %>
      <br>
      <p>
        アニメ：<%= t.title %>
      <br>
        感想：<%= t.message %>
      </p>
      <% if current_user %>
        <% if Like.find_by(user_id: current_user.id, anime_id: t.id) %>
          <%= link_to '😍️', like_path(t), method: :delete %>
        <% else %>
          <%= link_to 'ｲｲﾈ!️', likes_path(anime_id: t.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <% if current_user %>
        <% if Bad.find_by(user_id: current_user.id, anime_id: t.id) %>
          <%= link_to '😟', bad_path(t), method: :delete %>
        <% else %>
          <%= link_to 'ｳ~ﾝ…', bads_path(anime_id: t.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <% if current_user and t.user_id == current_user.id %>
        <%= link_to '削除', anime_path(t), method: :delete, data: { confirm: '削除していいですか？' } ,class: 'btn btn-primary' %>
        <%= link_to '編集', "animes/#{t.id}/edit", class: 'btn btn-primary' %>
      <% end %>
      <br>
      <br>
      <br>
    <%#<% end %>
  </p>
<% end %>
<br>
<br>

<h2>Goodランキング</h2>
<% @like_ranks.each do |t| %>
<%= image_tag 'hito.png', class:"profile_img", :size =>'40x40' %>
<%#<%= image_tag 'hito.png', class:"profile_img", :size =>'40x40' %>
<%#<%= image_tag "/get_image/#{t.id}" %>
<%= User.find(t.user_id).uid %>
<br>
<p>タイトル：<%= t.title %></p>
<p>内容：<%= t.message %></p>
<br>
<br>
<% end %>
<br>
<br>

<h2>Badランキング</h2>
<% @bad_ranks.each do |t| %>
<%= image_tag 'hito.png', class:"profile_img", :size =>'40x40' %>
<%#<%= image_tag 'hito.png', class:"profile_img", :size =>'40x40' %>
<%#<%= image_tag "/get_image/#{t.id}" %>
<%= User.find(t.user_id).uid %>
<br>
<p>タイトル：<%= t.title %></p>
<p>内容：<%= t.message %></p>
<br>
<br>
<% end %>
<br>
<br>

app/views/hf/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light mb-3 p-4" style="background-color:#33CC66;">
    <div class="nav-bar-brand nav-class">
        <h3>
            アニメを斬る
        </h3>
    </div>
    <ul class="navbar-nav ml-auto">
        <li class= "nav-item">
            <%= link_to 'ホーム', root_path, class: 'nav-link' %>
        </li>
        <li class= "nav-item">
            <%= link_to 'ユーザ一覧', users_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
            <li class= "nav-item"><%= link_to 'ログアウト', top_logout_path, class: 'nav-link' %></li>
        <% else %>
            <li class= "nav-item"><%= link_to 'ログイン', top_login_path, class: 'nav-link' %></li>
            <li class= "nav-item"><%= link_to 'サインアップ', new_user_path, class: 'nav-link' %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class= "header">
      <%= render "hf/header" %>
    </div> 
    
    <div class= "container">
      <div class= "main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/top/error.html.erb
<p>ログイン失敗</p>

<%= link_to 'Back', top_login_path, class: 'btn btn-primary' %>

app/views/top/login.html.erb
<div style= "margin-bottom:30px">
  <h1>ログイン画面</h1>
</div>

<% if flash[:notice] %>
  <p>
    <font color="blue">
      <%= flash[:notice] %>
    </font>
  </p>
<% end %>  

<h3>アニメを斬るにログインする</h3>
<%= form_with url: top_login_path, local: true do |f| %>
  <p>
    <%= f.label :uid, 'ユーザID' %>
    <%= f.text_field :uid, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass, class: 'form-control' %>
  </p>
  
  <p>
    <%= f.submit 'ログイン', class: 'btn-lg btn-success' %>
  </p>
<%end%>

<p>
  <%= link_to '新規登録', new_user_path, class: 'btn btn-primary' %>
</p>

<p>
  <%= link_to '戻る', :back, class: 'btn btn-primary' %>
</p>

app/views/users/edit.html.erb
<% if current_user %>
    <%= f.text_field :message %>
    <%= f.submit "編集" %>
<%end%>

<h1>内容編集</h1>
<%= form_for @user, url: {action: :update} do |f| %>
<%= f.text_field :message %>
  <br>
  <%= f.submit '投稿する'%>
<% end %>

app/views/users/index.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @users.each do |e| %>
<p>
  <%= e.uid %>
  <%= e.pass %>
  <%= link_to '削除', user_path(e), method: :delete, class: 'btn btn-primary'%>
</p>
<% end %>

<p><%= link_to 'ユーザ登録', new_user_path, class: 'btn btn-primary' %></p>

<p><%= link_to '戻る', animes_path, class: 'btn btn-primary' %></p>

app/views/users/new.html.erb
<div style= "margin-bottom:30px">
  <h1>新規登録</h1>
</div>

<%= form_for @user, url: {action: :create} do |f| %>
  <p>
   <%= f.label :uid, 'ユーザID' %>
   <%= f.text_field :uid, class: 'form-control'%>
  </p>

  <p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </p>

  <p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

  </p> 
 <%#  <%= form_for @anime do |f| %>
  <%#  <%= f.file_field :image %>
  <%#  <%= f.submit 'アップロードする'%>
 <%#  <% end %> 
 
  <%= form_tag("/users/#{@user.id}/get_image", {multipart: true}) do %>
    <!--<p>
      画像：
      <input name="image" type="file">
    </p>  
    -->  
    <p>
      <input type="submit" value="登録", class="btn-lg btn-success">
    </p>
    
  <% end %>

<% end %>

  <p><%= link_to '戻る', :back , class: 'btn btn-primary'%>